### ISSUE TITLE
Extract College Name / University

### ISSUE THREAD

**Issue by lokesh77** [OmkarPathak/ResumeParser#11]
Hi... @OmkarPathak .... Everything works fine in this project.... But I just want something To Do.... Need to extract Name of college or university..... Please guide me how to do this..

**Comment by OmkarPathak** [comment]
I have a [function](https://github.com/OmkarPathak/ResumeParser/blob/d956016a7e4382cd2b397d81a66b3f3ca334983b/resume_parser/resume_parser/utils.py#L87) which extracts all the text between entities. So you can print entities['education'] from that function which will give you all the contents for **education** section of the resume. Then you can have a list of colleges, brute force them with the contents and extract College / University names as required

**Comment by OmkarPathak** [comment]
@lokesh77 closing this issue. If you were able to modify the script and see it as a necessary part to be incorporated in the current, do open a pull request :)
