### ISSUE TITLE
can't get en-core-web-sm==2.0.0 and object-detection==0.1 via docker

### ISSUE THREAD

**Issue by loviji** [OmkarPathak/ResumeParser#14]
I tried in ubuntu 18.4, 18.10, 19.4 and pip can't get en-core-web-sm==2.0.0 when docker-compose executed.

**Comment by SaraMES** [comment]
change object-detection to object-detection-0.1 and that be working

**Comment by OmkarPathak** [comment]
Closing this as the new dockerfile works fine.
