### ISSUE TITLE
nltk download word return error

### ISSUE THREAD

**Issue by loviji** [OmkarPathak/ResumeParser#15]
`python -m nltk nltk.download('words')`
return an error 
bash: syntax error near unexpected token `('

**Comment by msd1810** [comment]
go to your environment's python console
import nltk & download
`>>> import nltk
>>> nltk.download('words')
[nltk_data] Downloading package words to /home/raja/nltk_data...
[nltk_data]   Unzipping corpora/words.zip.
True`

hope this works

**Comment by dynamiccarrots** [comment]
msd1810 - Can you explain what you mean by this, are you adding this to a file.

**Comment by msd1810** [comment]
> msd1810 - Can you explain what you mean by this, are you adding this to a file.

in your python console:
import nltk
nltk.download('words')

this will download dictionary words in your home folder, you can find nltk_data folder. this data is used for natural language processing

**Comment by OmkarPathak** [comment]
@loviji @dynamiccarrots are you able to solve this?

**Comment by dynamiccarrots** [comment]
I was yes, I'm not that experienced in Python and was not in the Python Console. 🤦‍♂

**Comment by OmkarPathak** [comment]
Closing this issue as you were able to solve the same.
