### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement en-core-web-sm==2.0.0 via docker

### ISSUE THREAD

**Issue by amanbabbar** [OmkarPathak/ResumeParser#19]
I am using Ubuntu 16.04. I tried by upgrading/downgrading en-core-web-sm package but got the same error every time.

**Comment by yaocanwei** [comment]
you can change the version which you have installed.

**Comment by amanbabbar** [comment]
I commented out this package in the requirements.txt file because we can install this package from pre_requisites.py script.

After doing this I got the same error with another package.

`ERROR: Could not find a version that satisfies the requirement object-detection==0.1`

**Comment by OmkarPathak** [comment]
@amanbabbar I have updated requirements.txt file. Can you try once now?

**Comment by OmkarPathak** [comment]
@amanbabbar any leads? If you were able to solve this issue, we can close this

**Comment by amanbabbar** [comment]
@OmkarPathak I did not check with a new requirements.txt file. for now, I have commented out unused packages form requiremets.txt file and its working fine. I am closing this issue.
