### ISSUE TITLE
Error on docker-compose up 

### ISSUE THREAD

**Issue by nursnaaz** [OmkarPathak/ResumeParser#23]
I am getting the following error while running the docker-compose

(python3.5) 671207523NB001:ResumeParser mnoordeen$ sudo docker-compose up -d 
Building web
Step 1/11 : FROM python:3
 ---> e497dabd8450
Step 2/11 : ENV PYTHONUNBUFFERED 1
 ---> Using cache
 ---> de3d41caadda
Step 3/11 : RUN mkdir -p /usr/src/app
 ---> Using cache
 ---> 55792868cd3a
Step 4/11 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 1c9b6d2112a8
Step 5/11 : COPY requirements.txt /usr/src/app
 ---> Using cache
 ---> 1514ca91001f
Step 6/11 : RUN pip install -r /usr/src/app/requirements.txt
 ---> Using cache
 ---> e38f9f560c17
Step 7/11 : COPY . /usr/src/app
 ---> Using cache
 ---> e8c9407a8c34
Step 8/11 : RUN python /usr/src/app/pre_requisites.py
 ---> Using cache
 ---> be5a2b962d6c
Step 9/11 : RUN python /usr/src/app/manage.py makemigrations
 ---> Running in 442789c1879c
Traceback (most recent call last):
  File "/usr/src/app/manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/app/manage.py", line 14, in <module>
    ) from exc
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
ERROR: Service 'web' failed to build: The command '/bin/sh -c python /usr/src/app/manage.py makemigrations' returned a non-zero code: 1

**Comment by OmkarPathak** [comment]
@nursnaaz I have fixed the issue. Can you please check and confirm
