### ISSUE TITLE
The syntax of the command is incorrect.

### ISSUE THREAD

**Issue by simplesaad** [OmkarPathak/ResumeParser#4]
C:\Users\moham\Desktop\Resume Parser\ResumeParser-master>python cli.py -f <C:\Users\moham\Desktop\Resume Parser\ResumeParser-master\resumes\Saad.pdf>
The syntax of the command is incorrect.

**Comment by OmkarPathak** [comment]
Remove < > from your file path and try again

**Comment by letrongtanbs** [comment]
how to import extract_utils as to_extract
I can't install  extract_utils

**Comment by OmkarPathak** [comment]
@letrongtanbs what error are you getting exactly?

**Comment by simplesaad** [comment]
when executing " C:\Users\moham\Desktop\Resume Parser\ResumeParser-master\resumes\a2.pdf"
I'm getting this error "cli.py: error: unrecognized arguments: Parser\ResumeParser-master\resumes\a2.pdf"

**Comment by OmkarPathak** [comment]
python cli.py -f "C:\Users\moham\Desktop\Resume Parser\ResumeParser-master\resumes\a2.pdf"

This is the write command. You are not passing it as a single argument. There is a space between **Resume Parser** folder name. Hence, windows interprets it as two different arguments

**Comment by simplesaad** [comment]
@OmkarPathak, I am getting this error.

C:\Users\moham\Desktop\Resume_Parser\ResumeParser-master>python cli.py -f C:\Users\moham\Desktop\Resume_Parser\ResumeParser-master\resumes\a2.pdf
C:\Users\moham\AppData\Local\Programs\Python\Python37-32\lib\importlib\_bootstrap.py:219: RuntimeWarning: cymem.cymem.Pool size changed, may indicate binary incompatibility. Expected 24 from C header, got 32 from PyObject
  return f(*args, **kwds)
C:\Users\moham\AppData\Local\Programs\Python\Python37-32\lib\importlib\_bootstrap.py:219: RuntimeWarning: cymem.cymem.Address size changed, may indicate binary incompatibility. Expected 12 from C header, got 20 from PyObject
  return f(*args, **kwds)
C:\Users\moham\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\__init__.py:91: RequestsDependencyWarning: urllib3 (1.24.1) or chardet (2.3.0) doesn't match a supported version!
  RequestsDependencyWarning)
[96m Extracting data from: C:\Users\moham\Desktop\Resume_Parser\ResumeParser-master\resumes\a2.pdf[00m
C:\Users\moham\AppData\Local\Programs\Python\Python37-32\lib\importlib\_bootstrap.py:219: RuntimeWarning: cymem.cymem.Pool size changed, may indicate binary incompatibility. Expected 24 from C header, got 32 from PyObject
  return f(*args, **kwds)
C:\Users\moham\AppData\Local\Programs\Python\Python37-32\lib\importlib\_bootstrap.py:219: RuntimeWarning: cymem.cymem.Address size changed, may indicate binary incompatibility. Expected 12 from C header, got 20 from PyObject
  return f(*args, **kwds)
Traceback (most recent call last):
  File "cli.py", line 63, in <module>
    pprint(cli_obj.extract_resume_data())
  File "cli.py", line 23, in extract_resume_data
    return self.__extract_from_file(args.file)
  File "cli.py", line 32, in __extract_from_file
    resume_parser = ResumeParser(file)
  File "C:\Users\moham\Desktop\Resume_Parser\ResumeParser-master\resume_parser\resume_parser.py", line 23, in __init__
    self.__text_raw    = utils.extract_text(self.__resume, os.path.splitext(self.__resume)[1])
**AttributeError: module 'utils' has no attribute 'extract_text'**

**Comment by letrongtanbs** [comment]
My fault, just because I changed the repository!
I solved it.
Thank you.

**Comment by OmkarPathak** [comment]
@letrongtanbs glad you could solve the issue. Do provide a feedback after you use the application 😄
