### ISSUE TITLE
config.cfg error on spacy > v3

### ISSUE THREAD

**Issue by saiflakhani** [OmkarPathak/ResumeParser#41]
The docker code compiles and builds successfully, however, the following message is shown:

![Screenshot 2021-02-24 at 1 01 01 PM](https://user-images.githubusercontent.com/22739244/108994959-71ce2380-76c2-11eb-9666-4eea72d9aaf4.png)

This error is due to changes made in spacy and en_core_web_sm in newer versions.

From StackOverflow: https://stackoverflow.com/questions/66149878/e053-could-not-read-config-cfg-resumeparser

I have fixed the issue and will be sending a PR

**Comment by kaiwalyaharkare** [comment]
pip install -U pip setuptools wheel
pip install -U spacy
python -m spacy download en_core_web_sm
 Do this

**Comment by mechen-gess** [comment]
> pip install -U pip setuptools wheel
> pip install -U spacy
> python -m spacy download en_core_web_sm
> Do this

When I do this in jupyter notebook I get a SyntaxError. When I tried to do the first line in cmd still some error occurs. Where are these lines supposed to run on?

**Comment by bgonzalezfractal** [comment]
@mechen-gess you need to run this in CLI, If you want these commands to work directly on your jupyter notebook then do this:
`!pip install -U pip setuptools wheel
!pip install -U spacy
!python -m spacy download en_core_web_sm`

Basically, you add an exclamation point to interact with command line, this will work on Google Colab as well.

**Comment by mechen-gess** [comment]
@bgonzalezfractal Thanks for your help!
