### ISSUE TITLE
AttributeError: module 'utils' has no attribute 'extract_text'

### ISSUE THREAD

**Issue by simplesaad** [OmkarPathak/ResumeParser#5]
@OmkarPathak, I am getting this error.

C:\Users\moham\Desktop\Resume_Parser\ResumeParser-master>python cli.py -f C:\Users\moham\Desktop\Resume_Parser\ResumeParser-master\resumes\a2.pdf
C:\Users\moham\AppData\Local\Programs\Python\Python37-32\lib\importlib_bootstrap.py:219: RuntimeWarning: cymem.cymem.Pool size changed, may indicate binary incompatibility. Expected 24 from C header, got 32 from PyObject
return f(*args, **kwds)
C:\Users\moham\AppData\Local\Programs\Python\Python37-32\lib\importlib_bootstrap.py:219: RuntimeWarning: cymem.cymem.Address size changed, may indicate binary incompatibility. Expected 12 from C header, got 20 from PyObject
return f(*args, **kwds)
C:\Users\moham\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests_init_.py:91: RequestsDependencyWarning: urllib3 (1.24.1) or chardet (2.3.0) doesn't match a supported version!
RequestsDependencyWarning)
�[96m Extracting data from: C:\Users\moham\Desktop\Resume_Parser\ResumeParser-master\resumes\a2.pdf�[00m
C:\Users\moham\AppData\Local\Programs\Python\Python37-32\lib\importlib_bootstrap.py:219: RuntimeWarning: cymem.cymem.Pool size changed, may indicate binary incompatibility. Expected 24 from C header, got 32 from PyObject
return f(*args, **kwds)
C:\Users\moham\AppData\Local\Programs\Python\Python37-32\lib\importlib_bootstrap.py:219: RuntimeWarning: cymem.cymem.Address size changed, may indicate binary incompatibility. Expected 12 from C header, got 20 from PyObject
return f(*args, **kwds)
Traceback (most recent call last):
File "cli.py", line 63, in 
pprint(cli_obj.extract_resume_data())
File "cli.py", line 23, in extract_resume_data
return self.__extract_from_file(args.file)
File "cli.py", line 32, in __extract_from_file
resume_parser = ResumeParser(file)
File "C:\Users\moham\Desktop\Resume_Parser\ResumeParser-master\resume_parser\resume_parser.py", line 23, in init
self.__text_raw = utils.extract_text(self.__resume, os.path.splitext(self.__resume)[1])
AttributeError: module 'utils' has no attribute 'extract_text'

**Comment by OmkarPathak** [comment]
@simplesaad can you attach a screenshot with all the paths visible. I am not able to get a clear idea about how and from where you are running the cli.py file. The above error seems to have the problem with path as it is not able to find the utils file

**Comment by simplesaad** [comment]
![image](https://user-images.githubusercontent.com/29461284/54177518-822a6b00-44b8-11e9-867e-ec15f61a03de.png)

**Comment by simplesaad** [comment]
This is my 'utils.py' file in the location [C:\Users\moham\Desktop\Resume_Parser\resume_parser\utils.py]
[utils.txt](https://github.com/OmkarPathak/ResumeParser/files/2955343/utils.txt)

**Comment by OmkarPathak** [comment]
@simplesaad I am running the same on Windows and everything works fine for me:
![image](https://user-images.githubusercontent.com/17998893/54179632-58287700-44bf-11e9-8e7e-902672e10e92.png)

**Comment by OmkarPathak** [comment]
@simplesaad any leads? If the issue still persists can you please provide a full specification of what all versions of Python are you using? So that I can reproduce this issue

**Comment by OmkarPathak** [comment]
@simplesaad  closing this as there was no response from you

**Comment by simplesaad** [comment]
@OmkarPathak , I'm running this on Windows 10 and Python 3.7.2. After the installation of dependencies and running $resume_parser/resume_parser/resume_parser.py , i tried running $python .\cli.py -f .\resumes\a2.pdf
![image](https://user-images.githubusercontent.com/29461284/55306553-4741a480-5472-11e9-811c-75b784e01f72.png)
Apologies for the late response.

**Comment by OmkarPathak** [comment]
@simplesaad  can you also provide the steps to recreate this issue. I am unable to recreate the same issue in my environment

**Comment by simplesaad** [comment]
Is it possible for you to join for a teamviewer session to check it out in my environment?

**Comment by OmkarPathak** [comment]
Can we have a skype session?

**Comment by simplesaad** [comment]
any other desktop sharing service?

**Comment by simplesaad** [comment]
My skype contact is : mohammedsaadua@gmail.com

**Comment by deependrabannaji** [comment]
Hi @OmkarPathak  I'm getting the same error

**Comment by zluna095** [comment]
Getting the same error here
