### ISSUE TITLE
"There is no item named 'word/document.xml' in the archive"

### ISSUE THREAD

**Issue by lokesh77** [OmkarPathak/ResumeParser#7]
Hi, I tried of Extracting Information from Doc file Format... It only works with Pdf and Docx format....
Please do guide me for implementing Doc file.
![Screenshot from 2019-03-13 16-54-24](https://user-images.githubusercontent.com/18551600/54275675-3e675c80-45b1-11e9-9ded-093120605c9c.png)
![Screenshot from 2019-03-13 16-55-23](https://user-images.githubusercontent.com/18551600/54275677-3efff300-45b1-11e9-9c85-2232c499eb23.png)

**Comment by OmkarPathak** [comment]
@lokesh77 Yes currently we only supprt `docx` and `pdf` files. We are planning to support `doc` and `odt` files in near future :smile:

**Comment by lokesh77** [comment]
@OmkarPathak Bro, Currently I'm trying to implement doc files for my project. Please do Guide any suggestion...

**Comment by sanpreet** [comment]
Hello @OmkarPathak, I hope you are doing great. I was also struck on the same problem while the uploaded file is **docx not doc**. As per you saying, it supports **.docx** but such is not happening in my case. It is looking for the packages in the below files
`
/home/gpu/Desktop/All_projects/django_Nlp/testingapplication/djangonlp-master/django_Nlp',
 '/home/gpu/Desktop/All_projects/django_Nlp/djangolearnenv/lib/python36.zip',
 '/home/gpu/Desktop/All_projects/django_Nlp/djangolearnenv/lib/python3.6',
 '/home/gpu/Desktop/All_projects/django_Nlp/djangolearnenv/lib/python3.6/lib-dynload',
 '/usr/lib/python3.6',
 '/home/gpu/Desktop/All_projects/django_Nlp/djangolearnenv/lib/python3.6/site-packages'
`
Any help is highly appreciated.

With Regards
Sanpreet Singh

**Comment by IDrei** [comment]
> @lokesh77 Yes currently we only supprt `docx` and `pdf` files. We are planning to support `doc` and `odt` files in near future

Hello @OmkarPathak ! 
Thanks a lot for your work!
Have you already added support for .doc format? 
Hope, you'll say YES.

**Comment by OmkarPathak** [comment]
@IDrei Yes now we do support .doc
Only condition is that .doc is supported only on Linux and Mac. Windows is not supported. For more info visit [https://github.com/OmkarPathak/pyresparser#supported-file-formats](https://github.com/OmkarPathak/pyresparser#supported-file-formats)

**Comment by IDrei** [comment]
@OmkarPathak 
Thank you!
Do you plan to add windows service?

**Comment by OmkarPathak** [comment]
> @OmkarPathak
> Thank you!
> Do you plan to add windows service?

We use [textract](https://textract.readthedocs.io/en/stable/python_package.html) for extracting DOC files. It doesn't support yet. If they release windows compatible version in future, we can also accommodate the same in the code

**Comment by IDrei** [comment]
> > @OmkarPathak
> > Thank you!
> > Do you plan to add windows service?
> 
> We use [textract](https://textract.readthedocs.io/en/stable/python_package.html) for extracting DOC files. It doesn't support yet. If they release windows compatible version in future, we can also accommodate the same in the code

I've read this in readme. I supposed, that [textract](https://textract.readthedocs.io/en/stable/python_package.html) is your product too. Sorry!
