### ISSUE TITLE
To store Web page Table data to JSON data

### ISSUE THREAD

**Issue by lokesh77** [OmkarPathak/ResumeParser#9]
@OmkarPathak ...Hi, Is there any technique to store the Django Web page Output (Table) data to Json output in local path???

**Comment by OmkarPathak** [comment]
@lokesh77 any leads on this issue?

**Comment by lokesh77** [comment]
Hi... @OmkarPathak  I found a method to store it in any formats. I just used MongoDB to with the Django Application and retrieved the output in as JSON file.
